# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/all-your-base-are-belong-to/project>
	:perl_version_from _:main ;
	:version_from _:main ;
	:readme_from _:main ;
	:test_requires "Test::More 0.61", "File::Basename", "File::Spec", "Data::Dumper" ;
	:requires "parent", "version 0.77".

_:main <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/all/your/base/are/belong/to.pm" .

